PAGE_TYPE_HTML = "HTML"
PAGE_TYPE_FRONTIER = "FRONTIER"
PAGE_TYPE_DUPLICATE = "DUPLICATE"
PAGE_TYPE_BINARY = "BINARY"

DATA_TYPE_PDF = "PDF"
DATA_TYPE_DOC = "DOC"
DATA_TYPE_DOCX = "DOCX"
DATA_TYPE_PPT = "PPT"
DATA_TYPE_PPTX = "PPTX"

PARSE_STATUS_PARSED: str = "PARSED"
PARSE_STATUS_NOT_PARSED: str = "NOT_PARSED"
PARSE_STATUS_PARSING: str = "PARSING"

DEFAULT_CRAWL_DELAY_SECONDS = 5

OLDER_THAN_SECONDS_WHEN_PARSING = 30 * 60

USERNAME = "fri"
PASSWORD = "fri-pass"

TERMINAL_COLORS = ['\033[95m', '\033[94m', '\033[96m', '\033[92m', '\033[93m', '\033[91m', '\033[1m', '\033[4m']
END_COLOR = '\033[0m'
