PAGE_TYPE_HTML = "HTML"
PAGE_TYPE_FRONTIER = "FRONTIER"
PAGE_TYPE_DUPLICATE = "DUPLICATE"
PAGE_TYPE_BINARY = "BINARY"

DATA_TYPE_PDF = "PDF"
DATA_TYPE_DOC = "DOC"
DATA_TYPE_DOCX = "DOCX"
DATA_TYPE_PPT = "PPT"
DATA_TYPE_PPTX = "PPTX"

PARSE_STATUS_PARSED: str = "PARSED"
PARSE_STATUS_NOT_PARSED: str = "NOT_PARSED"
PARSE_STATUS_PARSING: str = "PARSING"
